//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiCSUserControl.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class View : global::System.Configuration.ApplicationSettingsBase {
        
        private static View defaultInstance = ((View)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new View())));
        
        public static View Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("121")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
              [
              {
              ""ColumnID"":""UserName"",
              ""ColumnText"":""UserName"",
              ""ColumnName"":""UserName"",
              ""WidthPercent"":100,
              ""Align"":""center"",
              ""IsShow"":1
              },
              {
              ""ColumnID"":""UserID"",
              ""ColumnText"":"""",
              ""ColumnName"":""UserID"",
              ""WidthPercent"":0,
              ""Align"":""center"",
              ""IsShow"":0
              }
              ]
            ")]
        public string UserLoginModule_DGV {
            get {
                return ((string)(this["UserLoginModule_DGV"]));
            }
            set {
                this["UserLoginModule_DGV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n              [{\"ID\":\"Name\",\"CanNull\":\"false\",\"Reg\":\"\",\"Err\":\"名称不允许为空，请填写\"},\r\n " +
            "             {\"ID\":\"PWD\",\"CanNull\":\"false\",\"Reg\":\"\",\"Err\":\"密码不允许为空，请填写\"}]\r\n     " +
            "       ")]
        public string UserLogin_ControlInfo {
            get {
                return ((string)(this["UserLogin_ControlInfo"]));
            }
            set {
                this["UserLogin_ControlInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                  [\r\n                  {\r\n                  \"ColumnID\":\"Name\",\r" +
            "\n                  \"ColumnText\":\"名称\",\r\n                  \"ColumnName\":\"Name\",\r\n " +
            "                 \"WidthPercent\":40,\r\n                  \"Align\":\"left\",\r\n        " +
            "          \"IsShow\":1\r\n                  },\r\n                  {\r\n               " +
            "   \"ColumnID\":\"Model\",\r\n                  \"ColumnText\":\"型号\",\r\n                  " +
            "\"ColumnName\":\"Model\",\r\n                  \"WidthPercent\":40,\r\n                  \"" +
            "Align\":\"left\",\r\n                  \"IsShow\":1\r\n                  },\r\n            " +
            "      {\r\n                  \"ColumnID\":\"Count\",\r\n                  \"ColumnText\":\"" +
            "数量\",\r\n                  \"ColumnName\":\"Count\",\r\n                  \"WidthPercent\":" +
            "20,\r\n                  \"Align\":\"left\",\r\n                  \"IsShow\":1\r\n          " +
            "        },\r\n                  {\r\n                  \"ColumnID\":\"ProductID\",\r\n    " +
            "              \"ColumnText\":\"\",\r\n                  \"ColumnName\":\"ProductID\",\r\n   " +
            "               \"WidthPercent\":0,\r\n                  \"Align\":\"center\",\r\n         " +
            "         \"IsShow\":0\r\n                  },\r\n                  {\r\n                " +
            "  \"ColumnID\":\"ProcessId\",\r\n                  \"ColumnText\":\"\",\r\n                 " +
            " \"ColumnName\":\"ProcessId\",\r\n                  \"WidthPercent\":0,\r\n               " +
            "   \"Align\":\"center\",\r\n                  \"IsShow\":0\r\n                  },\r\n      " +
            "            {\r\n                  \"ColumnID\":\"MaterialID\",\r\n                  \"Co" +
            "lumnText\":\"\",\r\n                  \"ColumnName\":\"MaterialID\",\r\n                  \"" +
            "WidthPercent\":0,\r\n                  \"Align\":\"center\",\r\n                  \"IsShow" +
            "\":0\r\n                  }\r\n                  ]\r\n                ")]
        public string ProcessMaterial_DGV {
            get {
                return ((string)(this["ProcessMaterial_DGV"]));
            }
            set {
                this["ProcessMaterial_DGV"] = value;
            }
        }
    }
}
